import type { Theme } from '@skeletonlabs/skeleton/themes';

const RoseGame = {
  "name": "RoseGame",
  "properties": {
    "--type-scale-factor": "1.067",
    "--type-scale-1": "calc(0.75rem * var(--type-scale-factor))",
    "--type-scale-2": "calc(0.875rem * var(--type-scale-factor))",
    "--type-scale-3": "calc(1rem * var(--type-scale-factor))",
    "--type-scale-4": "calc(1.125rem * var(--type-scale-factor))",
    "--type-scale-5": "calc(1.25rem * var(--type-scale-factor))",
    "--type-scale-6": "calc(1.5rem * var(--type-scale-factor))",
    "--type-scale-7": "calc(1.875rem * var(--type-scale-factor))",
    "--type-scale-8": "calc(2.25rem * var(--type-scale-factor))",
    "--type-scale-9": "calc(3rem * var(--type-scale-factor))",
    "--type-scale-10": "calc(3.75rem * var(--type-scale-factor))",
    "--type-scale-11": "calc(4.5rem * var(--type-scale-factor))",
    "--type-scale-12": "calc(6rem * var(--type-scale-factor))",
    "--type-scale-13": "calc(8rem * var(--type-scale-factor))",
    "--base-font-color": "var(--color-surface-950)",
    "--base-font-color-dark": "var(--color-surface-50)",
    "--base-font-family": "Inter, Roboto, Helvetica Neue, Arial Nova, Nimbus Sans, Arial, sans-serif",
    "--base-font-size": "inherit",
    "--base-line-height": "inherit",
    "--base-font-weight": "inherit",
    "--base-font-style": "normal",
    "--base-letter-spacing": "0em",
    "--heading-font-color": "inherit",
    "--heading-font-color-dark": "inherit",
    "--heading-font-family": "system-ui, sans-serif",
    "--heading-font-weight": "700",
    "--heading-font-style": "normal",
    "--heading-letter-spacing": "inherit",
    "--anchor-font-color": "var(--color-primary-500)",
    "--anchor-font-color-dark": "var(--color-primary-500)",
    "--anchor-font-family": "inherit",
    "--anchor-font-size": "inherit",
    "--anchor-line-height": "inherit",
    "--anchor-font-weight": "inherit",
    "--anchor-font-style": "inherit",
    "--anchor-letter-spacing": "inherit",
    "--anchor-text-decoration": "none",
    "--anchor-text-decoration-hover": "underline",
    "--anchor-text-decoration-active": "none",
    "--anchor-text-decoration-focus": "none",
    "--space-scale-factor": "1",
    "--radii-default": "6px",
    "--radii-container": "12px",
    "--border-width-default": "1px",
    "--divide-width-default": "1px",
    "--outline-width-default": "1px",
    "--ring-width-default": "2px",
    "--body-background-color": "var(--color-surface-50)",
    "--body-background-color-dark": "var(--color-surface-950)",
    "--color-primary-50": "255 181 169",
    "--color-primary-100": "251 153 147",
    "--color-primary-200": "248 125 124",
    "--color-primary-300": "244 96 102",
    "--color-primary-400": "241 68 79",
    "--color-primary-500": "237 40 57",
    "--color-primary-600": "209 32 46",
    "--color-primary-700": "181 24 34",
    "--color-primary-800": "153 16 23",
    "--color-primary-900": "125 8 11",
    "--color-primary-950": "97 0 0",
    "--color-primary-contrast-dark": "var(--color-surface-50)",
    "--color-primary-contrast-light": "var(--color-primary-50)",
    "--color-primary-contrast-50": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-100": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-200": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-300": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-400": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-500": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-600": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-700": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-800": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-900": "var(--color-primary-contrast-dark)",
    "--color-primary-contrast-950": "var(--color-primary-contrast-dark)",
    "--color-secondary-50": "244 255 223",
    "--color-secondary-100": "218 243 199",
    "--color-secondary-200": "193 231 174",
    "--color-secondary-300": "167 219 150",
    "--color-secondary-400": "142 207 125",
    "--color-secondary-500": "116 195 101",
    "--color-secondary-600": "93 171 81",
    "--color-secondary-700": "70 148 61",
    "--color-secondary-800": "46 124 40",
    "--color-secondary-900": "23 101 20",
    "--color-secondary-950": "0 77 0",
    "--color-secondary-contrast-dark": "var(--color-secondary-950)",
    "--color-secondary-contrast-light": "var(--color-secondary-50)",
    "--color-secondary-contrast-50": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-100": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-200": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-300": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-400": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-500": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-600": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-700": "var(--color-secondary-contrast-dark)",
    "--color-secondary-contrast-800": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-900": "var(--color-secondary-contrast-light)",
    "--color-secondary-contrast-950": "var(--color-secondary-contrast-light)",
    "--color-tertiary-50": "255 255 151",
    "--color-tertiary-100": "255 237 121",
    "--color-tertiary-200": "255 219 91",
    "--color-tertiary-300": "255 201 60",
    "--color-tertiary-400": "255 183 30",
    "--color-tertiary-500": "255 165 0",
    "--color-tertiary-600": "228 143 0",
    "--color-tertiary-700": "201 120 0",
    "--color-tertiary-800": "173 98 0",
    "--color-tertiary-900": "146 75 0",
    "--color-tertiary-950": "119 53 0",
    "--color-tertiary-contrast-dark": "var(--color-tertiary-950)",
    "--color-tertiary-contrast-light": "var(--color-tertiary-50)",
    "--color-tertiary-contrast-50": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-100": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-200": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-300": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-400": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-500": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-600": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-700": "var(--color-tertiary-contrast-dark)",
    "--color-tertiary-contrast-800": "var(--color-tertiary-contrast-light)",
    "--color-tertiary-contrast-900": "var(--color-tertiary-contrast-light)",
    "--color-tertiary-contrast-950": "var(--color-tertiary-contrast-light)",
    "--color-success-50": "255 255 249",
    "--color-success-100": "228 255 224",
    "--color-success-200": "200 255 198",
    "--color-success-300": "173 255 173",
    "--color-success-400": "145 255 147",
    "--color-success-500": "118 255 122",
    "--color-success-600": "94 230 98",
    "--color-success-700": "71 204 73",
    "--color-success-800": "47 179 49",
    "--color-success-900": "24 153 24",
    "--color-success-950": "0 128 0",
    "--color-success-contrast-dark": "var(--color-success-950)",
    "--color-success-contrast-light": "var(--color-success-50)",
    "--color-success-contrast-50": "var(--color-success-contrast-dark)",
    "--color-success-contrast-100": "var(--color-success-contrast-dark)",
    "--color-success-contrast-200": "var(--color-success-contrast-dark)",
    "--color-success-contrast-300": "var(--color-success-contrast-dark)",
    "--color-success-contrast-400": "var(--color-success-contrast-dark)",
    "--color-success-contrast-500": "var(--color-success-contrast-dark)",
    "--color-success-contrast-600": "var(--color-success-contrast-dark)",
    "--color-success-contrast-700": "var(--color-success-contrast-dark)",
    "--color-success-contrast-800": "var(--color-success-contrast-dark)",
    "--color-success-contrast-900": "var(--color-success-contrast-dark)",
    "--color-success-contrast-950": "var(--color-success-contrast-light)",
    "--color-warning-50": "255 255 169",
    "--color-warning-100": "255 252 135",
    "--color-warning-200": "254 248 101",
    "--color-warning-300": "254 245 68",
    "--color-warning-400": "253 241 34",
    "--color-warning-500": "253 238 0",
    "--color-warning-600": "226 214 0",
    "--color-warning-700": "199 190 0",
    "--color-warning-800": "172 165 0",
    "--color-warning-900": "145 141 0",
    "--color-warning-950": "118 117 0",
    "--color-warning-contrast-dark": "var(--color-warning-950)",
    "--color-warning-contrast-light": "var(--color-warning-50)",
    "--color-warning-contrast-50": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-100": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-200": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-300": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-400": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-500": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-600": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-700": "var(--color-warning-contrast-dark)",
    "--color-warning-contrast-800": "var(--color-warning-contrast-light)",
    "--color-warning-contrast-900": "var(--color-warning-contrast-light)",
    "--color-warning-contrast-950": "var(--color-warning-contrast-light)",
    "--color-error-50": "255 213 150",
    "--color-error-100": "249 188 127",
    "--color-error-200": "243 163 104",
    "--color-error-300": "238 138 80",
    "--color-error-400": "232 113 57",
    "--color-error-500": "226 88 34",
    "--color-error-600": "199 70 27",
    "--color-error-700": "172 53 20",
    "--color-error-800": "145 35 14",
    "--color-error-900": "118 18 7",
    "--color-error-950": "91 0 0",
    "--color-error-contrast-dark": "var(--color-error-950)",
    "--color-error-contrast-light": "var(--color-error-50)",
    "--color-error-contrast-50": "var(--color-error-contrast-dark)",
    "--color-error-contrast-100": "var(--color-error-contrast-dark)",
    "--color-error-contrast-200": "var(--color-error-contrast-dark)",
    "--color-error-contrast-300": "var(--color-error-contrast-dark)",
    "--color-error-contrast-400": "var(--color-error-contrast-dark)",
    "--color-error-contrast-500": "var(--color-error-contrast-light)",
    "--color-error-contrast-600": "var(--color-error-contrast-light)",
    "--color-error-contrast-700": "var(--color-error-contrast-light)",
    "--color-error-contrast-800": "var(--color-error-contrast-light)",
    "--color-error-contrast-900": "var(--color-error-contrast-light)",
    "--color-error-contrast-950": "var(--color-error-contrast-light)",
    "--color-surface-50": "255 255 255",
    "--color-surface-100": "224 224 224",
    "--color-surface-200": "194 194 194",
    "--color-surface-300": "163 163 163",
    "--color-surface-400": "133 133 133",
    "--color-surface-500": "102 102 102",
    "--color-surface-600": "85 85 85",
    "--color-surface-700": "68 68 68",
    "--color-surface-800": "51 51 51",
    "--color-surface-900": "34 34 34",
    "--color-surface-950": "17 17 17",
    "--color-surface-contrast-dark": "var(--color-surface-950)",
    "--color-surface-contrast-light": "var(--color-surface-50)",
    "--color-surface-contrast-50": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-100": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-200": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-300": "var(--color-surface-contrast-dark)",
    "--color-surface-contrast-400": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-500": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-600": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-700": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-800": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-900": "var(--color-surface-contrast-light)",
    "--color-surface-contrast-950": "var(--color-surface-contrast-light)"
  },
  "metadata": {
    "version": "3.0.0"
  }
} satisfies Theme;

export default RoseGame;